# fly.toml app configuration file generated for mysterious on 2025-02-22T12:04:29+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mysterious'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
